NinjaMVC.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NinjaMVC.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index() => View();
    }
}

NinjaMVC.Web/Controllers/NinjaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NinjaMVC.Domain;

namespace NinjaMVC.Web.Controllers
{
    public class NinjaController : Controller
    {
        // GET: Ninja
        public ActionResult Index()
        {
            List<Ninja> ninjas;
            using (var ctx = new NinjaContext())
            {
                ninjas = ctx.Ninjas.ToList();
            }
            return View(ninjas);
        }

        //GET: Ninja by ID
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Ninja ninja;
            using (var ctx = new NinjaContext())
            {
                ninja = ctx.Ninjas.Find(id);
            }

            return ninja == null ? HttpNotFound() : (ActionResult)View(ninja);
        }

        //GET Create Ninja form
        public ActionResult Create() => View();

        //POST Created Ninja
        [HttpPost]
        public ActionResult Create(Ninja newNinja)
        {
            using (var ctx = new NinjaContext())
            {
                ctx.Ninjas.Add(newNinja);
                ctx.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

NinjaMVC.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>NINJA MANAGER</h1>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            Select an item in the menu bar to get started.
        </p>
    </div>
</div>

NinjaMVC.Web/Views/Ninja/Create.cshtml
@model NinjaMVC.Domain.Ninja

<h2>Create A Ninja</h2>

@using (Html.BeginForm())
{
<div class="form-horizontal">
    <div class="form-group">
        @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.PostalCode, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.HouseNumber, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.HouseNumber, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>


}

NinjaMVC.Web/Views/Ninja/Details.cshtml
@model NinjaMVC.Domain.Ninja

<h2>@Model.Name</h2>
<table class="table">
    <tr>
        <th>@Html.LabelFor(model => model.PostalCode)</th>
        <td>@Model.PostalCode</td>
    </tr>
    <tr>
        <th>@Html.LabelFor(model => model.HouseNumber)</th>
        <td>@Model.HouseNumber</td>
    </tr>
    <tr>
        <th>@Html.LabelFor(model => model.Identifier)</th>
        <td>@Model.Identifier</td>
    </tr>
</table>

@Html.ActionLink("Back to overview", "Index", "Ninja", null, new {@class="btn btn-primary"})

NinjaMVC.Web/Views/Ninja/Index.cshtml
@model IEnumerable<NinjaMVC.Domain.Ninja>

<h2>Ninjas</h2>

@Html.ActionLink("Create a Ninja", "Create", "Ninja", null, new { @class = "btn btn-primary" })

<table class="table">
    <tr>
        <th>@Html.LabelFor(model => model.FirstOrDefault().Name)</th>
        <th></th>
    </tr>
    @foreach (var ninja in Model)
    {
        <tr>
            <td>@ninja.Name</td>
            <td>@Html.ActionLink("Details", "Details", "Ninja", new { id = ninja.Identifier }, null)</td>
        </tr>
    }
</table>

NinjaMVC.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Ninjas", "Index", "Ninja")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>